### ISSUE TITLE
Could not download from Udemy with version 2.3.1

### ISSUE THREAD

**Issue by VuNguyen102** [nhtera/udemy-dl-windows#3]
I have try to download many courses from Udemy but always got an errors as picture below.
![image](https://cloud.githubusercontent.com/assets/17152694/15701137/b0c23270-2802-11e6-960c-af0c4855cdcf.png)

**Comment by nhtera** [comment]
Sad news! You're Too Late.
Udemy had fixed the api (23/03/2016). This program no longer working. I poked around the api, however all the endpoints used to grab files now return 403/Unauthorized response.
If anyone figures out how to bypass it, message me and i'll update the program.
